version: "3.9"

networks:
  flight-net:
    driver: bridge

services:

  # ── Zookeeper (wajib ada sebelum Kafka) ──────────────────
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    networks: [flight-net]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # ── Kafka Broker ──────────────────────────────────────────
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    networks: [flight-net]
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:29092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  # ── Kafka UI (monitor data di http://localhost:8080) ──────
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks: [flight-net]
    depends_on: [kafka]
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  # ── Flight Producer (Anggota 1) ───────────────────────────
  flight-producer:
    build: ./Producer
    container_name: flight-producer
    networks: [flight-net]
    depends_on:
      kafka:
        condition: service_healthy
    env_file: .env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    restart: on-failure

  # ── Redis (output sink Spark → Anggota 4 visualisasi) ────
  redis:
    image: redis:7.2-alpine
    container_name: redis
    networks: [flight-net]
    ports:
      - "6379:6379"

  # ── Spark Processor (Anggota 2) ───────────────────────────
  spark-processor:
    build: ./Spark
    container_name: spark-processor
    networks: [flight-net]
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=commercial-flight-stream
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MODEL_PATH=/app/model_keterlambatan
    volumes:
      # Mount folder model agar hasil training bisa dipakai
      - ./Spark/model_keterlambatan:/app/model_keterlambatan
      # Mount checkpoint agar stream bisa resume setelah restart
      - ./Spark/checkpoint_spark:/app/checkpoint_spark
    restart: on-failure
